# Travis CI build script - test on all supported platforms
os: linux
dist: xenial
language: python
jobs:
  include:
    - name: "Linux"
      script:
        - make coverage
      after_success:
        - coveralls
    - name: "macOS"
      os: osx
      osx_image: xcode11.6
      language: shell
      script:
        - make PYTHON=python3 test
      install:
        - pip3 install -U pip wheel coverage coveralls
        - pip3 install . --no-binary faiss-cpu
        - python3 --version
    - name: "Windows"
      os: windows
      language: shell
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      before_install:
        - choco install make
        - choco install python --version 3.6.8
        - python -m pip install -U pip wheel
        - python -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
install:
  - pip install -U pip wheel coverage coveralls
  - pip install .
  - python --version
script:
  - make test
