# GitHub Actions build workflow
name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies - MacOS
        run: brew install libomp
        if: matrix.os == 'macos-latest'

      - name: Install dependencies - Windows
        run: |
          python -m pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
          pip install git+https://github.com/huggingface/transformers
        if: matrix.os == 'windows-latest'

      - name: Build
        run: |
          pip install -U pip==20.2.4 wheel coverage coveralls
          pip install .
          python --version
          make coverage

      - name: Test Coverage
        run: coveralls
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
