name: txtai build

on: ["push", "pull_request"]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: python -m pip install -U pip wheel
      - run: pip install -U pip wheel coverage
      - run: pip install .
      - run: python --version
      - run: make coverage

      # Generate test coverage reports
      - run: coveralls
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

#  windows:
#    runs-on: windows-latest

#    steps:
#      - uses: actions/checkout@v2
#      - run: python -m pip install -U pip wheel
#      - run: python -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
#      - run: pip install -U pip wheel coverage
#      - run: pip install .
#      - run: python --version
#      - run: make test
