name: txtai

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      # macos pre-install
      - run: brew install libomp
        if: ${{ matrix.os == 'ubuntu-latest'}}

      # Windows pre-install
      - run: python -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        if: ${{ matrix.os == 'windows-latest'}}

      # Common steps
      - run: pip install -U pip wheel coverage coveralls
      - run: pip install .
      - run: python --version || python --version
      - run: make coverage

      # Only create test coverage once
      - run: coveralls
        if: ${{ matrix.os == 'ubuntu-latest'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
